### ISSUE TITLE
HIP-RA-X Documentation errors

### ISSUE THREAD

**Issue by malcolm-dsider** [softwareengineerprogrammer/geothermal-ui#14]
1) In the HIP-RA reference documentation section, the units for "Reservoir Pressure" are wrong - they are listed as mPa (milli Pascals) but should be MPa (mega Pascals).
2) "Recoverable Heat from Rock" has as a comment: "percent of fluid that is recoverable from the reservoir (0.75 = 75%)" - it should say: "percent of heat that is recoverable from the rock (0.75 = 75%)"

**Comment by softwareengineerprogrammer** [comment]
@malcolm-dsider This is fixed in UI, please see corresponding GEOPHIRES PR - https://github.com/NREL/GEOPHIRES-X/pull/293. (The UI consumes schema files from GEOPHIRES as documented in [CONTRIBUTING](https://github.com/NREL/GEOPHIRES-X/blob/main/CONTRIBUTING.rst#schema-files).)

![image](https://github.com/user-attachments/assets/4a1443f4-3261-438a-9a0b-86ccafef5a4d)
